spring.application.name=springboot-aws-localstack

# aws
aws.s3.bucket=my-bucket
aws.sqs.queue=my-queue
aws.dynamodb.table=Items
aws.ses.sender=test@example.com

# rds (LocalStack)
aws.rds.instance=localstack-postgres
aws.rds.dbName=demo
aws.rds.username=postgres
aws.rds.password=postgres

# lambda
aws.lambda.functionName=demo-function
aws.lambda.runtime=java17
aws.lambda.handler=com.example.demo.lambda.LambdaHandler::handleRequest

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
