spring.application.name=springboot-aws-localstack

# aws
aws.s3.bucket=my-bucket
aws.sqs.queue=my-queue
aws.dynamodb.table=Items


spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
